Generate the simulation data

In [2]:
import numpy as np

# Number of simulations to run (it's fast, don't worry):
ns = 10000
# Potential (see below for options)
sim = 'r1'
# Number of nodes
n = 3
# Dimension
dim = 2
# Number of time steps
nt = 1000


#Standard simulation sets:
n_set = [4, 8]
sim_sets = [
 {'sim': 'r1', 'dt': [5e-3], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'r2', 'dt': [1e-3], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'spring', 'dt': [1e-2], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'string', 'dt': [1e-2], 'nt': [1000], 'n': [30], 'dim': [2]},
 {'sim': 'charge', 'dt': [1e-3], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'superposition', 'dt': [1e-3], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'damped', 'dt': [2e-2], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
 {'sim': 'discontinuous', 'dt': [1e-2], 'nt': [1000], 'n': n_set, 'dim': [2, 3]},
]


#Select the hand-tuned dt value for a smooth simulation
# (since scales are different in each potential):
dt = [ss['dt'][0] for ss in sim_sets if ss['sim'] == sim][0]

title = '{}_n={}_dim={}_nt={}_dt={}'.format(sim, n, dim, nt, dt)
print('Running on', title)

Running on r1_n=3_dim=2_nt=1000_dt=0.005


In [3]:
from simulate import SimulationDataset
s = SimulationDataset(sim, n=n, dim=dim, nt=nt//2, dt=dt)
# Update this to your own dataset, or regenerate:
base_str = './'
data_str = title
s.simulate(ns)

1


In [4]:
data = s.data
s.data.shape

(10000, 500, 3, 6)

Data (batch, time, particles, total dimension)
- batch: `ns` number of simulations 
- time: `self.times` trajectory timesteps 
- particles: `n` number of particles
- attributes (`2*dim + params`):
    - first `dim`: position coordinates
    - second `dim`: velocity coordinates
    - `params` values: (mass or charge)

In [9]:
masses = s.data[5][1, :, -1]
masses

Array([1.7545208, 1.7860682, 2.0619895], dtype=float32)

In [10]:
accel_data = s.get_acceleration()


In [12]:
import torch

X = torch.from_numpy(np.concatenate([s.data[:, i] for i in range(0, s.data.shape[1], 5)]))
y = torch.from_numpy(np.concatenate([accel_data[:, i] for i in range(0, s.data.shape[1], 5)]))

In [1]:
from generate_data import generate_data

X, y =  generate_data(save = True)

1


In [2]:
X[0]

tensor([[ 1.0040, -0.9063, -0.7482, -1.1714, -0.8712,  1.8019],
        [ 0.7239, -1.0256,  1.6616, -1.8910, -1.2889,  1.1429],
        [-1.1530,  0.2393,  1.7448,  0.5050,  0.5951,  0.6232]])

In [1]:
from generate_data import load_data

X, y = load_data("datasets/r1_n=3_dim=2_nt=1000_dt=0.005")

1


In [2]:
X[0]

tensor([[ 1.0040, -0.9063, -0.7482, -1.1714, -0.8712,  1.8019],
        [ 0.7239, -1.0256,  1.6616, -1.8910, -1.2889,  1.1429],
        [-1.1530,  0.2393,  1.7448,  0.5050,  0.5951,  0.6232]])

In [3]:
X.shape

torch.Size([1000000, 3, 6])

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False)